FROM openjdk:8-jdk-alpine
MAINTAINER isacc codingdebugallday@163.com

COPY target/course-edge-service-1.0-SNAPSHOT.jar /jars/course-edge-service.jar

ENTRYPOINT ["java", "-jar", "/jars/course-edge-service.jar"]